services:
  jupyter:
    build: .
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/app/workspace
    command: >
      uv run jupyter lab
        --ip=0.0.0.0
        --port=8888
        --allow-root
        --NotebookApp.token=${JUPYTER_TOKEN}
    env_file:
      - .env
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
